#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: healthy-api_development
  user: postgres
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

test:
  <<: *default
  database: healthy-api_test
  user: postgres
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

production:
  <<: *default
  database: healthy-api_production
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
